fix: issue-9
I removed the v1 Java SDK versions of the X-Ray dependencies. I don't think these are required.

I think the issue came about because aws-xray-recorder-sdk-aws-sdk-core was a runtime dependency and not compile. This caused a NoClassDefFoundError exception during local testing.