fix: issue-92
The issue came about because aws-xray-recorder-sdk-aws-sdk-core was a runtime dependency and not compile. This caused a NoClassDefFoundError exception during local testing.